accounts/urls.py
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('edit/', views.profile_edit, name="profile_edit"),
    path('password_change/', views.password_change, name='password_change'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import TemplateView
from django_pydenticon.views import image as pydenticon_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>/', pydenticon_image, name='pydenticon_image'),
    path('', login_required(TemplateView.as_view(template_name='root.html')), name='root'),
    path('', include('instagram.urls'), name='instagram'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

instagram/urls.py
from django.urls import path, re_path
from . import views

app_name = 'instagram'

urlpatterns = [
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.shortcuts import resolve_url


class User(AbstractUser):
    # django 3에서 가능한 문법
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"

    website_url = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=13,
                                    validators=[RegexValidator(r"^010[1-9]\d{7}$")],
                                    blank=True,
                                    help_text="'-'를 제외한 숫자를 입력해주세요.")
    gender = models.CharField(max_length=1,
                              choices=GenderChoices.choices,
                              blank=True)
    avatar = models.ImageField(blank=True, upload_to="accounts/avatar/%Y/%m/%d",
                               help_text="48px * 48px 크기의 png/jpg 파일을 업로드해주세요.")

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        else:
            return resolve_url("pydenticon_image", self.username)

instagram/models.py
# from accounts.models import User를 사용하기 보다 django.conf의 settings를 통해
# User 모델을 사용하자.
from django.conf import settings
from django.db import models
import re

from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='instagram/post/%Y/%m/%d')
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    # post_detail을 구현할 때
    def get_absolute_url(self):
        return reverse('instagram:post_detail', args=[self.pk])


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm,
                                       PasswordChangeForm as AuthPasswordChangeForm)

from .models import User


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    # 이미 등록된 이메일 확인
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'last_name', 'first_name', 'website_url', 'bio', 'phone_number', 'gender']


class PasswordChangeForm(AuthPasswordChangeForm):
    def clean_new_password2(self):
        old_password = self.clean_old_password()
        new_password2 = super().clean_new_password2()
        if old_password == new_password2:
            raise forms.ValidationError('새로운 암호는 기존 암호와 다르게 입력해주세요.')
        return new_password2

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, logout_then_login,
                                       PasswordChangeView as AuthPasswordChangeView, )
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from .forms import SignupForm, ProfileForm, PasswordChangeForm

login = LoginView.as_view(template_name='accounts/login_form.html')


def logout(request):
    messages.success(request, '로그아웃 되었습니다.')
    return logout_then_login(request)


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            signed_user = form.save()
            auth_login(request, signed_user)
            messages.success(request, '회원가입을 환영합니다.')
            next_url = request.GET.get('next', '/')
            return redirect(next_url)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form
    })


@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '프로필이 수정되었습니다.')
            return redirect('profile_edit')
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'accounts/profile_edit_form.html', {
        'form': form
    })


class PasswordChangeView(LoginRequiredMixin, AuthPasswordChangeView):
    success_url = reverse_lazy('password_change')
    # 유저 수정 관련은 어드민 페이지를 보여주기 때문에 템플릿 지정해야함
    template_name = 'accounts/password_change_form.html'
    form_class = PasswordChangeForm

    def form_valid(self, form):
        messages.success(self.request, '암호를 변경했습니다.')
        return super().form_valid(form)


password_change = PasswordChangeView.as_view()

instagram/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Tag
from .form import PostForm


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            # extract tag name (model.py 참고)
            # 중간 테이블에 insert 되야하기 때문에 post가 저장되고 pk가 있어야함
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, '포스팅을 작성했습니다.')
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'instagram/post_form.html', {
        'form': form
    })


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'instagram/post_detail.html', {
        'post': post
    })


@login_required
def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)
    post_list = Post.objects.filter(author=page_user)
    return render(request, 'instagram/user_page.html', {
        'page_user': page_user,
        'post_list': post_list,
    })

accounts/templates/accounts/login_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include '_form.html' with form_title="로그인" submit_label="로그인" %}
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include '_form.html' with form_title="암호 변경" submit_label="암호 변경" %}
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_edit_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include '_form.html' with form_title="프로필 수정" submit_label="프로필 수정" %}
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include '_form.html' with submit_label="회원가입" %}
            </div>
        </div>
    </div>
{% endblock %}

config/templates/_form.html
{% load bootstrap4 %}

<div class="card">
    {% if form_title %}
        <div class="card-header">
            {{ form_title }}
        </div>
    {% endif %}
    <div class="card-body">
        {% if form %}
            <form actions="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">
                    {{ submit_label|default:"Submit" }}
                </button>
            </form>
        {% else %}
            <div class="alert alert-danger">
                form 객체를 지정해주세요.
            </div>
        {% endif %}

    </div>
</div>

config/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Instagram</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
{% endif %}

<div class="border-bottom mb-3">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="d-flex flex-column flex-md-row align-items-center justify-content-between p-3 px-md-4 bg-white">
                    <h5 class="h5 my-0 me-md-auto fw-normal">
                        <svg class="mr-1" fill="#262626" height="24" viewBox="0 0 48 48" width="24">
                            <path d="M13.86.13A17 17 0 008 1.26 11 11 0 003.8 4 12.22 12.22 0 001 8.28 18 18 0 00-.11 14.1c-.13 2.55-.13 3.38-.13 9.9s0 7.32.13 9.9A18 18 0 001 39.72 11.43 11.43 0 003.8 44 12.17 12.17 0 008 46.74a17.75 17.75 0 005.82 1.13c2.55.13 3.38.13 9.9.13s7.32 0 9.9-.13a17.82 17.82 0 005.83-1.13A11.4 11.4 0 0043.72 44a11.94 11.94 0 002.78-4.24 17.7 17.7 0 001.13-5.82c.13-2.55.13-3.38.13-9.9s0-7.32-.13-9.9a17 17 0 00-1.13-5.86A11.31 11.31 0 0043.72 4a12.13 12.13 0 00-4.23-2.78A17.82 17.82 0 0033.66.13C31.11 0 30.28 0 23.76 0s-7.31 0-9.9.13m.2 43.37a13.17 13.17 0 01-4.47-.83 7.25 7.25 0 01-2.74-1.79 7.25 7.25 0 01-1.79-2.74 13.23 13.23 0 01-.83-4.47c-.1-2.52-.13-3.28-.13-9.7s0-7.15.13-9.7a12.78 12.78 0 01.83-4.44 7.37 7.37 0 011.79-2.75A7.35 7.35 0 019.59 5.3a13.17 13.17 0 014.47-.83c2.52-.1 3.28-.13 9.7-.13s7.15 0 9.7.13a12.78 12.78 0 014.44.83 7.82 7.82 0 014.53 4.53 13.12 13.12 0 01.83 4.44c.13 2.51.13 3.27.13 9.7s0 7.15-.13 9.7a13.23 13.23 0 01-.83 4.47 7.9 7.9 0 01-4.53 4.53 13 13 0 01-4.44.83c-2.51.1-3.28.13-9.7.13s-7.15 0-9.7-.13m19.63-32.34a2.88 2.88 0 102.88-2.88 2.89 2.89 0 00-2.88 2.88M11.45 24a12.32 12.32 0 1012.31-12.35A12.33 12.33 0 0011.45 24m4.33 0a8 8 0 118 8 8 8 0 01-8-8"></path>
                        </svg>
                        <a href="{% url 'root' %}">
                            <img src="{% static 'logo.png' %}" alt="Instagram" style="width: 100px"/>
                        </a>
                    </h5>
                    <nav class="my-2 my-md-0 me-md-3">
                        <a class="p-2 text-dark" href="/explorer">
                            <svg aria-label="사람 찾기" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48"
                                 width="24">
                                <path clip-rule="evenodd"
                                      d="M24 .5C37 .5 47.5 11 47.5 24S37 47.5 24 47.5.5 37 .5 24 11 .5 24 .5zm0 44c11.3 0 20.5-9.2 20.5-20.5S35.3 3.5 24 3.5 3.5 12.7 3.5 24 12.7 44.5 24 44.5zm-4.4-23.7c.3-.5.7-.9 1.2-1.2l14.8-8.1c.3-.1.6-.1.8.1.2.2.3.5.1.8l-8.1 14.8c-.3.5-.7.9-1.2 1.2l-14.8 8.1c-.3.1-.6.1-.8-.1-.2-.2-.3-.5-.1-.8l8.1-14.8zm6.2 5l4.3-7.8-7.8 4.3 3.5 3.5z"
                                      fill-rule="evenodd"></path>
                            </svg>
                        </a>
                        <a class="p-2 text-dark" href="#">
                            <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48"
                                 width="24">
                                <path clip-rule="evenodd"
                                      d="M34.3 3.5C27.2 3.5 24 8.8 24 8.8s-3.2-5.3-10.3-5.3C6.4 3.5.5 9.9.5 17.8s6.1 12.4 12.2 17.8c9.2 8.2 9.8 8.9 11.3 8.9s2.1-.7 11.3-8.9c6.2-5.5 12.2-10 12.2-17.8 0-7.9-5.9-14.3-13.2-14.3zm-1 29.8c-5.4 4.8-8.3 7.5-9.3 8.1-1-.7-4.6-3.9-9.3-8.1-5.5-4.9-11.2-9-11.2-15.6 0-6.2 4.6-11.3 10.2-11.3 4.1 0 6.3 2 7.9 4.2 3.6 5.1 1.2 5.1 4.8 0 1.6-2.2 3.8-4.2 7.9-4.2 5.6 0 10.2 5.1 10.2 11.3 0 6.7-5.7 10.8-11.2 15.6z"
                                      fill-rule="evenodd"></path>
                            </svg>
                        </a>
                        <a class="p-2 text-dark" href="{% url "profile_edit" %}">
                            <img src="{{ user.avatar_url }}" class="rounded-circle" style="width: 24px; height: 24px;" />
                        </a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="border-top mt-3">
    <div class="container">
    <footer class=" my-md-4 ">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">© 2017-2020</small>
            </div>
            <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="link-secondary" href="#">Cool stuff</a></li>
                    <li><a class="link-secondary" href="#">Random feature</a></li>
                    <li><a class="link-secondary" href="#">Team feature</a></li>
                    <li><a class="link-secondary" href="#">Stuff for developers</a></li>
                    <li><a class="link-secondary" href="#">Another one</a></li>
                    <li><a class="link-secondary" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="link-secondary" href="#">Resource</a></li>
                    <li><a class="link-secondary" href="#">Resource name</a></li>
                    <li><a class="link-secondary" href="#">Another resource</a></li>
                    <li><a class="link-secondary" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="link-secondary" href="#">Team</a></li>
                    <li><a class="link-secondary" href="#">Locations</a></li>
                    <li><a class="link-secondary" href="#">Privacy</a></li>
                    <li><a class="link-secondary" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
</div>


</body>
</html>

config/templates/root.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                Instagram
                <hr/>
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">새 포스팅 작성</a>
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <img src="{{ post.author.avatar_url }}" class="rounded-circle" style="width: 34px; border-radius: 50%;"/>
                        {{ post.author.name }}
                    </div>
                    <dic class="card-body">
                        <img src="{{ post.photo.url }}"  style="width: 100%;"/>
                    </dic>
                    <div class="card-footer">
                        {% for tag in post.tag_set.all %}
                            <span class="badge badge-primary">
                                #{{ tag.name }}
                            </span>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include '_form.html' with form_title="새 포스트 작성" submit_label="새 포스트 작성" %}
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/user_page.html
{% extends 'instagram/layout.html' %}
{% block content %}
    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.avatar_url }}" class="rounded-circle" style="width: 160px; "/>
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                <a href="{% url 'profile_edit' %}" class="btn btn-secondary btn-sm">Edit Profile</a>
                <hr/>
                0 posts, 0 followers, 0 following
                <hr/>
                {{ page_user.name }}
            </div>
        </div>
        <div class="row mt-3">
            {% for post in post_list %}
                <div class="col-sm-4">
                    <img src="{{ post.photo.url }}" alt="{{ post.caption }}" style="width: 100%;"/>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}